POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name":"Rick Sanches",
    "age":"60",
    "email":"RickSanches@gmail.com"
}

###
GET https://nodejs-mongodb-api-dev-xepqs.3.us-1.fl0.io/api/users HTTP/1.1

###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/65c3b06e7f1a3ee2f9c3142a HTTP/1.1

###
PUT http://localhost:3000/api/users/65c3b06e7f1a3ee2f9c3142a HTTP/1.1
Content-Type: application/json

{
    "name":"Ivan Tahay",
    "age":"90",
    "email":"tahayk3@gmail.com" 
}

###
DELETE http://localhost:3000/api/users/65c3bbe39ea98a943cbe5e39 HTTP/1.1



